[package]
name = "norted-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
color-eyre.workspace = true
crossterm.workspace = true
futures-util.workspace = true
norted-core = { path = "../norted-core" }
ratatui.workspace = true
tokio.workspace = true
