[package]
name = "norted-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde_json.workspace = true
color-eyre.workspace = true
crossterm.workspace = true
futures-util.workspace = true
norted-core = { path = "../norted-core" }
norted-engine = { path = "../norted-engine" }
norted-model-library = { path = "../norted-model-library" }
ratatui = { workspace = true, features = ["unstable-rendered-line-info"] }
tokio.workspace = true
unicode-width.workspace = true
unicode-segmentation.workspace = true
