[package]
name = "norted-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
bytes.workspace = true
futures-util.workspace = true
norted-core = { path = "../norted-core" }
norted-engine = { path = "../norted-engine" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
tower = { version = "0.5.2", features = ["util"] }
