[package]
name = "scala-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
directories.workspace = true
fs2.workspace = true
getrandom.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tempfile.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
walkdir.workspace = true
uuid.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true
