#!/usr/bin/env python3
"""Build deterministic notices and MPL sources from checksum-verified locked crates.

Run cargo fetch --locked first. No network, license templates, or inferred owners.
Includes the entire lockfile graph (also build/dev/other-platform dependencies),
so the same conservative bundle can be used for all five packaging targets.
"""
import hashlib
import io
import json
from pathlib import Path
import re
import shutil
import subprocess
import tarfile
import tomllib

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / 'target/release-legal'
SUPPLEMENTS = ROOT / 'release/legal-upstream'
LEGAL = re.compile(r'(?i)^(licen[cs]e|copying|copyright|notice|unlicense|authors)([._-]|$)')


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def main():
    metadata = json.loads(subprocess.check_output(
        ['cargo', 'metadata', '--locked', '--offline', '--format-version=1'], cwd=ROOT))
    locked = tomllib.loads((ROOT / 'Cargo.lock').read_text())['package']
    checksums = {(p['name'], p['version']): p['checksum'] for p in locked if 'source' in p}
    supplements = json.loads((SUPPLEMENTS / 'manifest.json').read_text())
    notices = [
        'Scala third-party notices\n',
        'Generated by scripts/release-legal.py from Cargo.lock. Includes all locked\n'
        'registry packages, a conservative superset of every target and build.\n'
        'SPDX expressions below are upstream declarations, not relicensing. Where\n'
        'an OR choice exists, Scala uses MIT if offered, otherwise Apache-2.0 if\n'
        'offered; other expressions retain their stated terms and exceptions.\n'
        'All discovered upstream license/notice files are reproduced below.\n'
        'Source URLs and hashes are in DEPENDENCIES.json.\n\n'
        'MPL corresponding source: this archive includes unmodified .crate source\n'
        'archives in mpl-sources/ for every dependency declaring MPL. These are\n'
        'gzip-compressed tar archives containing the preferred form for modification\n'
        'and original license notices. option-ext and smartstring remain MPL-licensed;\n'
        'termina also offers MIT. Source rights are not restricted by Scala licensing.\n'
        'Redistributors must preserve notices and source availability, and supply\n'
        'any modifications to MPL-covered files under the MPL.\n'
    ]
    dependencies = []
    sources = {}
    used = set()
    for p in sorted(metadata['packages'], key=lambda p: (p['name'], p['version'])):
        if p['source'] is None:
            if p['id'] not in metadata['workspace_members']:
                raise ValueError(f"Unreviewed local dependency: {p['name']}")
            continue
        if p['source'] != 'registry+https://github.com/rust-lang/crates.io-index':
            raise ValueError(f"Unreviewed dependency source: {p['source']}")
        name, version = p['name'], p['version']
        if not p['license']:
            raise ValueError(f'Missing license declaration: {name} {version}')
        directory = Path(p['manifest_path']).parent
        registry = directory.parent.parent.parent
        archive_name = f'{name}-{version}.crate'
        archive = registry / 'cache' / directory.parent.name / archive_name
        data = archive.read_bytes()
        checksum = checksums[(name, version)]
        if sha256(data) != checksum:
            raise ValueError(f'Locked source checksum mismatch: {archive_name}')
        files = []
        with tarfile.open(fileobj=io.BytesIO(data), mode='r:gz') as package:
            for member in sorted(package.getmembers(), key=lambda m: m.name):
                path = Path(member.name)
                if member.isfile() and (LEGAL.match(path.name) or any(
                        x.lower() in ('licenses', 'licences') for x in path.parts[1:-1])):
                    content = package.extractfile(member).read()
                    files.append((str(Path(*path.parts[1:])), content, 'locked crate'))
        for row in supplements:
            if (row['package'], row['version']) == (name, version):
                content = (SUPPLEMENTS / row['file']).read_bytes()
                if sha256(content) != row['sha256']:
                    raise ValueError(f"Supplement checksum mismatch: {row['file']}")
                files.append((row['file'], content, row['url']))
                used.add(row['file'])
        if not files:
            raise ValueError(f'Missing upstream license files: {name} {version}')
        notices.append(f'\n{"=" * 72}\n{name} {version}\nLicense: {p["license"]}\n'
                       f'Repository: {p["repository"] or "not declared"}\n')
        for path, content, origin in files:
            notices.append(f'\n--- {path} ({origin}) ---\n{content.decode("utf-8")}\n')
        dependencies.append({'name': name, 'version': version, 'license': p['license'],
                             'repository': p['repository'], 'sha256': checksum,
                             'source': f'https://static.crates.io/crates/{name}/{archive_name}',
                             'notices': [{'path': path, 'sha256': sha256(content), 'origin': origin}
                                         for path, content, origin in files]})
        if 'MPL' in p['license']:
            sources[archive_name] = data
    if used != {row['file'] for row in supplements}:
        raise ValueError('Stale license supplements: review dependency changes')
    # Only replace output after all inputs pass; remove obsolete generated files.
    if OUTPUT.exists():
        shutil.rmtree(OUTPUT)
    (OUTPUT / 'mpl-sources').mkdir(parents=True)
    (OUTPUT / 'THIRD-PARTY-NOTICES.txt').write_text(''.join(notices), encoding='utf-8', newline='\n')
    (OUTPUT / 'DEPENDENCIES.json').write_text(json.dumps(dependencies, indent=2) + '\n', encoding='utf-8', newline='\n')
    for name, data in sources.items():
        (OUTPUT / 'mpl-sources' / name).write_bytes(data)
    print(f'Generated notices for {len(dependencies)} locked dependencies and {len(sources)} MPL source archives')


if __name__ == '__main__':
    main()
